/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next')['BAlert']
    BBadge: typeof import('bootstrap-vue-next')['BBadge']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormInvalidFeedback: typeof import('bootstrap-vue-next')['BFormInvalidFeedback']
    BFormRadioGroup: typeof import('bootstrap-vue-next')['BFormRadioGroup']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BPagination: typeof import('bootstrap-vue-next')['BPagination']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BSpinner: typeof import('bootstrap-vue-next')['BSpinner']
    BTableSimple: typeof import('bootstrap-vue-next')['BTableSimple']
    BTbody: typeof import('bootstrap-vue-next')['BTbody']
    BTd: typeof import('bootstrap-vue-next')['BTd']
    BTh: typeof import('bootstrap-vue-next')['BTh']
    BThead: typeof import('bootstrap-vue-next')['BThead']
    BToaster: typeof import('bootstrap-vue-next')['BToaster']
    BTr: typeof import('bootstrap-vue-next')['BTr']
    CriteriaGroup: typeof import('./src/components/form/CriteriaGroup.vue')['default']
    CriteriaGroupItem: typeof import('./src/components/form/CriteriaGroupItem.vue')['default']
    FilterDetailsForm: typeof import('./src/components/form/FilterDetailsForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IBxsEdit: typeof import('~icons/bxs/edit')['default']
    IIconoirSortDown: typeof import('~icons/iconoir/sort-down')['default']
    IIconoirSortUp: typeof import('~icons/iconoir/sort-up')['default']
    Input: typeof import('./src/components/form/Input.vue')['default']
    ITypcnDelete: typeof import('~icons/typcn/delete')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    RadioGroup: typeof import('./src/components/form/RadioGroup.vue')['default']
    SimpleDialog: typeof import('./src/components/dialog/SimpleDialog.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBTooltip: typeof import('bootstrap-vue-next')['vBTooltip']
  }
}
